services:
  - type: web
    name: fitness-tracker-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fitness-tracker-db
          property: connectionString

  - type: web
    name: fitness-tracker-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://fitness-tracker-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: fitness-tracker-db
    databaseName: fitness_tracker
    user: fitness_user
    plan: free
